ClassBaseLoginView/ecsite_project/accounts/urls.py
from django.urls import path
from .views import (
    RegistUserView, HomeView, UserLoginView,
    UserLogoutView, UserView
)

app_name = 'accounts'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', RegistUserView.as_view(), name='regist'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    path('user/', UserView.as_view(), name='user'),
]

ClassBaseLoginView/ecsite_project/ecsite_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('stores/', include('stores.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ClassBaseLoginView/ecsite_project/stores/urls.py
from django.urls import path
from .views import (
    ProductListView,ProductDetailView
)

app_name='stores'
urlpatterns=[
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_detail/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
]

ClassBaseLoginView/ecsite_project/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.urls import reverse_lazy


class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('Enter Email')
        user = self.model(
            username=username,
            email=email
        )
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, username, email, password=None):
        user = self.model(
            username = username,
            email = email,
        )
        user.set_password(password)
        user.is_staff=True
        user.is_active=True
        user.is_superuser=True
        user.save(using=self._db)
        return user


class Users(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=150)
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def get_absolute_url(self):
        return reverse_lazy('accounts:home')

ClassBaseLoginView/ecsite_project/stores/models.py
from django.db import models


class ProductTypes(models.Model):
    name = models.CharField(max_length=1000)

    class Meta:
        db_table = 'product_types'

    def __str__(self):
        return self.name


class Manufacturers(models.Model):
    name = models.CharField(max_length=1000)

    class Meta:
        db_table='manufacturers'

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=1000)
    price = models.IntegerField()
    stock = models.IntegerField()
    product_type = models.ForeignKey(
        ProductTypes, on_delete=models.CASCADE
    )
    manufacturer = models.ForeignKey(
        Manufacturers, on_delete = models.CASCADE
    )

    class Meta:
        db_table = 'products'

    def __str__(self):
        return self.name


class ProductPictures(models.Model):
    picture = models.FileField(upload_to='product_pictures/')
    product = models.ForeignKey(
        Products, on_delete = models.CASCADE
    )
    order = models.IntegerField()

    class Meta:
        db_table = 'product_pictures'
        #orderカラムを使って昇順に並び替え
        ordering = ['order']   

    def __str__(self):
        return self.product.name + ': ' + str(self.order)

ClassBaseLoginView/ecsite_project/accounts/forms.py
from django import forms
from .models import Users
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import AuthenticationForm

class RegistForm(forms.ModelForm):
    username = forms.CharField(label = '名前')
    age = forms.IntegerField(label = '年齢', min_value=0)
    email = forms.EmailField(label = 'メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput)

    class Meta:
        model = Users
        fields = ['username', 'age', 'email', 'password']

    def save(self, commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

# class UserLoginForm(forms.Form):
#     email = forms.EmailField(label = 'mailaddress')
#     password = forms.CharField(label = 'パスワード', widget = forms.PasswordInput)

class UserLoginForm(AuthenticationForm):
    username = forms.EmailField(label='email') #メールアドレスをもとに判断しているためemail入力
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    remember = forms.BooleanField(label = 'ログイン状態を保持する', required=False)

ClassBaseLoginView/ecsite_project/accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import (CreateView, FormView)
from django.views.generic.base import TemplateView, View
from .forms import RegistForm, UserLoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView

class HomeView(TemplateView):
    template_name = 'home.html'


class RegistUserView(CreateView):
    template_name = 'regist.html'
    form_class = RegistForm


class UserLoginView(FormView):
    template_name = 'user_login.html'
    form_class = UserLoginForm

    def post(self, request, *args, **kwargs):
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email, password=password)
        next_url = request.POST['next']
        if user is not None and user.is_active:
            login(request, user)
        if next_url:
            return redirect(next_url)
        return redirect('accounts:home')




class UserLoginView(LoginView):
    template_name = 'user_login.html'
    authentication_form = UserLoginForm

    def form_valid(self, form):
        remember = form.cleaned_data['remember']
        if remember:
            self.request.session.set_expiry(1200000)
        return super().form_valid(form)

class UserLogoutView(LogoutView):
    pass

class UserView(LoginRequiredMixin, TemplateView):
    template_name = 'user.html'
    #@method_decorator
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)  

ClassBaseLoginView/ecsite_project/stores/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
import os
from .models import (
    Products,
)




class ProductListView(LoginRequiredMixin, ListView):
    model = Products
    template_name = os.path.join('stores', 'product_list.html')
    
    #検索欄で絞り込む
    def get_queryset(self): 
        query = super().get_queryset()
        product_type_name = self.request.GET.get('product_type_name', None)
        product_name = self.request.GET.get('product_name', None)
        if product_type_name:
            #nameカラムで絞り込み
            query = query.filter(
                product_type__name = product_type_name
            )
        
        if product_name:
            query = query.filter(
                name = product_name
            )
        order_by_price = self.request.GET.get('order_by_price', 0)
        if order_by_price == '1':
            query = query.order_by('price')
        elif order_by_price == '2':
            query = query.order_by('-price')
        return query

        

    #viewに渡す
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_type_name'] = self.request.GET.get('product_type_name', '')
        context['product_name'] = self.request.GET.get('product_name', '')
        order_by_price = self.request.GET.get('order_by_price')
        if order_by_price == '1':
            context['ascending'] = True
        elif order_by_price == '2':
            context['descending'] = True
        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Products
    template_name = os.path.join('stores', 'product_detail.html')

ClassBaseLoginView/ecsite_project/templates/base.html
<!DOCTYPE html>
<html lang="ja"> 
<head> 
  <meta charset="utf-8"> 
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head> 

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'accounts:home' %}">ホーム</a>
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'accounts:user_logout' %}">ログアウト</a>
    <a class="navbar-brand" href="{% url 'stores:product_list' %}">商品一覧</a>
    {% else %}
    <a class="navbar-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
    <a class="navbar-brand" href="{% url 'accounts:regist' %}">登録</a>
    {% endif %}
   <a class="navbar-brand" href="{% url 'accounts:user' %}">ユーザー画面</a>
  </nav>
  {% block content %}{% endblock %}
</body> 
</html>

ClassBaseLoginView/ecsite_project/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>ホーム画面です</h1>
{% endblock %}

ClassBaseLoginView/ecsite_project/templates/regist.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p}}
  <input type="submit" value="ユーザー登録">
</form>
{% endblock %}

ClassBaseLoginView/ecsite_project/templates/stores/product_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="col-6 offset-3">
  <div style="float: left; padding: 0 20px 20px 0">
    <!-- 1対多で結びついているため、productpictures_set -->
    {% for picture in object.productpictures_set.all %}
        {% if forloop.first %}
          <div><img width="200px" height="200px" src={{ picture.picture.url }}></div>
        {% else %}
            <img width="50px" height="50px" src={{ picture.picture.url }}>
        {% endif %}
    {% endfor %}
  </div>
  <div>
    <p>商品名: {{ object.name }}
    <p>値段: {{ object.price }}
    <p>残量: {{ object.stock }}
  </div>
</div>
{% endblock %}

ClassBaseLoginView/ecsite_project/templates/stores/product_list.html
{% extends 'base.html' %}
{% block content %}
<div class="col-10 offset-1">
<h2>商品一覧</h2>
<form method="get", action = "{% url 'stores:product_list' %}">
  <p>商品タイプ: <input type="text" name="product_type_name" value="{{ product_type_name }}"/></p>
  <p>商品名: <input type="text" name="product_name" value="{{ product_name }}"/></p>
  <p>値段で並び替える:
     昇順<input type="radio" name="order_by_price" value="1" {% if ascending %}checked{% endif %}>
     降順<input type="radio" name="order_by_price" value="2"{% if descending %}checked{% endif %}>
  </p>
  <p><input type="submit" value="検索"/></p>
</form>
<table class="table table-striped table-bordered">
<thead>
  <tr>
    <td>種類</td>
    <td>製品名</td>
    <td>値段</td>
    <td>在庫数</td>
    <td>製造元</td>
  </tr>
</thead>
<tbody>
{% for product in object_list %}
<tr>
<td>{{ product.product_type.name }}</td>
<td><a href="{% url 'stores:product_detail' pk=product.id %}">{{ product.name }}</a></td>
<td>{{ product.price }}円</td>
<td>{{ product.stock }}個</td>
<td>{{ product.manufacturer.name }}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>

{% endblock %}

ClassBaseLoginView/ecsite_project/templates/user.html
{% extends 'base.html' %}
{% block content %}
<h1>ユーザー画面です。ログインが必要な画面です</h1>
{% endblock %}

ClassBaseLoginView/ecsite_project/templates/user_login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p}}
  <input type="hidden" name="next" value="{{ request.GET.next}}">
  <input type="submit" value="ログイン">
</form>
{% endblock %}